def query_user_for_member(members):
    member = input("Enter the club member name: ")
    if member not in members:
        print("Name", member, "not found.")
    else:
        return member


def print_recommendations(reader, friends, recommended_books):
    print(f"Recommendations for {reader}:")
    for book in recommended_books:
        print(f"\t{book[1]} by {book[0]}")
    print(f"List generated by recommendations of {friends[0]} and {friends[1]}")
